# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171023_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knnlist',
            name='firstDetail',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='knnlist',
            name='objectName',
            field=models.CharField(max_length=255),
        ),
    ]
